### ISSUE TITLE
Component should be able to handle attachment information via the message body

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/csv-component#48]

**Comment by kirill-levitskiy** [comment]
This URL is service information and can confuse non-experienced end-user, because the URL can't be opened through Internet network. Probably, such client will write a ticket to the support channel, because the attachment can't be retrieved due to 404.
Moreover, we haven't implemented such approach in other components. What kind of case have you faced where you need to pass the steward URL through the message body?

**Comment by jhorbulyk** [comment]
Closing in favor of #95
